### ISSUE TITLE
[Combobox] Design feedback

### ISSUE THREAD

**Issue by akdetrick** [narmi/design_system#1044]
Via Slack (Hillary)

> - Chevron doesn’t open up dropdown (it also looks like a disabled color?)
> - Should clear out selected input from field if you open it again. (You should still see the check but a user should be able to type something else)
> - Chevrons aren’t matching up/diff sizes

![WdfI66qg](https://github.com/narmi/design_system/assets/231252/7b83b057-b2ee-4173-8223-16918694c9f6)

## TODO

- [x] Input clearing behavior
- [x] Add `endContent` prop for a freeform content slot
- [x] Update `Combobox` and `Select` to use `endContent` for the chevron
- [x] Update ` Combobox.Category` and `Select.Category` to use same color and size icon
